services:
  postgres:
    image: postgres:15
    container_name: forkup_db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ???
      POSTGRES_USER: ???
      POSTGRES_PASSWORD: ???

volumes:
  postgres_data: