services:
  postgres:
    image: postgres:15
    container_name: forkup_db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: forkup_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: FoRkUpRM371055

volumes:
  postgres_data: